### ISSUE TITLE
unable to resolve dependency tree

### ISSUE THREAD

**Issue by ianchanning** [eduardoborges/use-mask-input#2]
Hi there, this looks like an interesting project but it looks like its stuck on React v16
```
$ npm install use-mask-input --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @mona-health-app/client@undefined
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from use-mask-input@1.0.2
npm ERR! node_modules/use-mask-input
npm ERR!   use-mask-input@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

**Comment by eduardoborges** [comment]
> Hi there, this looks like an interesting project but it looks like its stuck on React v16
> 
> ```
> $ npm install use-mask-input --save
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: @mona-health-app/client@undefined
> npm ERR! Found: react@17.0.2
> npm ERR! node_modules/react
> npm ERR!   react@"17.0.2" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^16.13.1" from use-mask-input@1.0.2
> npm ERR! node_modules/use-mask-input
> npm ERR!   use-mask-input@"*" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> ```

Hey, @ianchanning i take this week to update this lib, its happening <3
