### ISSUE TITLE
Thanks for this package! 🙏 🎉

### ISSUE THREAD

**Issue by benjaminwaterlot** [eduardoborges/use-mask-input#34]
Hi Eduardo!

Just wanted to thank you for the lib - it seems to work very well (currently testing with 3.2.0 on Next.js), and I really think it's answering a need in the React ecosystem, where I searched for a while for a solution for input masking integrated with RHF.

It seems to work great both with uncontrolled inputs (using `withHookFormMask`) and controlled inputs (using RHF's Controller and `ref={withMask(...))`).

Thanks again!! 🙏

**Comment by focux** [comment]
Great work @eduardoborges. Also, I was wondering how to use this with RHF's controlled inputs, thanks @benjaminwaterlot.
