### ISSUE TITLE
TypeError: Inputmask is not a function

### ISSUE THREAD

**Issue by NandoBruch** [eduardoborges/use-mask-input#36]
Estou utilizando o hook em uma aplicação que usa Next 13. 

A implementação segue o exemplo mostrado no readme.

```
import { useForm } from 'react-hook-form';
import { useHookFormMask } from 'use-mask-input';

type FormType = {
  guest: any;
  cpf: string;
};

type FormProps = {
  submit: (data: FormType) => void;
};

const Form: FC<FormProps> = ({ submit, ...props }) => {
  const { register, handleSubmit } = useForm<FormType>({
    defaultValues: {
      guest: '',
      cpf: ''
    }
  });
  const registerWithMask = useHookFormMask(register);

  const onSubmit = (data: FormType) => {
    submit(data);
  };
  return (
    <div {...props}>
      <h3>titulo</h3>
      <form onSubmit={handleSubmit(data => onSubmit(data))}>
        <TextInput
          {...registerWithMask('cpf', 'cpf')}
          label='CPF'
        />
...
```

Rodando localmente, ao carregar a página, o erro recebido é:
![image](https://github.com/eduardoborges/use-mask-input/assets/47747571/c7977e03-2b7e-4ed9-bf05-3a8edde61d19)
![image](https://github.com/eduardoborges/use-mask-input/assets/47747571/c8cb09cb-8bd9-4877-a6a8-0cd93bf873e2)

**Comment by eduardoborges** [comment]
> Estou utilizando o hook em uma aplicação que usa Next 13.
> 
> A implementação segue o exemplo mostrado no readme.
> 
> ```
> import { useForm } from 'react-hook-form';
> import { useHookFormMask } from 'use-mask-input';
> 
> type FormType = {
>   guest: any;
>   cpf: string;
> };
> 
> type FormProps = {
>   submit: (data: FormType) => void;
> };
> 
> const Form: FC<FormProps> = ({ submit, ...props }) => {
>   const { register, handleSubmit } = useForm<FormType>({
>     defaultValues: {
>       guest: '',
>       cpf: ''
>     }
>   });
>   const registerWithMask = useHookFormMask(register);
> 
>   const onSubmit = (data: FormType) => {
>     submit(data);
>   };
>   return (
>     <div {...props}>
>       <h3>titulo</h3>
>       <form onSubmit={handleSubmit(data => onSubmit(data))}>
>         <TextInput
>           {...registerWithMask('cpf', 'cpf')}
>           label='CPF'
>         />
> ...
> ```
> 
> Rodando localmente, ao carregar a página, o erro recebido é: ![image](https://user-images.githubusercontent.com/47747571/250695306-c7977e03-2b7e-4ed9-bf05-3a8edde61d19.png) ![image](https://user-images.githubusercontent.com/47747571/250695361-c8cb09cb-8bd9-4877-a6a8-0cd93bf873e2.png)

Poderia mostrar como está seu package.json?

**Comment by NandoBruch** [comment]
> > Estou utilizando o hook em uma aplicação que usa Next 13.
> > A implementação segue o exemplo mostrado no readme.
> > ```
> > import { useForm } from 'react-hook-form';
> > import { useHookFormMask } from 'use-mask-input';
> > 
> > type FormType = {
> >   guest: any;
> >   cpf: string;
> > };
> > 
> > type FormProps = {
> >   submit: (data: FormType) => void;
> > };
> > 
> > const Form: FC<FormProps> = ({ submit, ...props }) => {
> >   const { register, handleSubmit } = useForm<FormType>({
> >     defaultValues: {
> >       guest: '',
> >       cpf: ''
> >     }
> >   });
> >   const registerWithMask = useHookFormMask(register);
> > 
> >   const onSubmit = (data: FormType) => {
> >     submit(data);
> >   };
> >   return (
> >     <div {...props}>
> >       <h3>titulo</h3>
> >       <form onSubmit={handleSubmit(data => onSubmit(data))}>
> >         <TextInput
> >           {...registerWithMask('cpf', 'cpf')}
> >           label='CPF'
> >         />
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Rodando localmente, ao carregar a página, o erro recebido é: ![image](https://user-images.githubusercontent.com/47747571/250695306-c7977e03-2b7e-4ed9-bf05-3a8edde61d19.png) ![image](https://user-images.githubusercontent.com/47747571/250695361-c8cb09cb-8bd9-4877-a6a8-0cd93bf873e2.png)
> 
> Poderia mostrar como está seu package.json?

 "dependencies": {
    "@phosphor-icons/react": "^2.0.9",
    "@stitches/react": "^1.2.8",
    "@types/node": "18.14.2",
    "@types/react": "18.0.28",
    "@types/react-dom": "18.0.11",
    "axios": "^1.3.4",
    "dotenv": "^16.0.3",
    "eslint-config-next": "13.2.1",
    "inputmask": "^5.0.9-beta.16",
    "next": "13.2.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.43.9",
    "typescript": "4.9.5",
    "use-mask-input": "^3.3.0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.54.0",
    "@typescript-eslint/parser": "^5.54.0",
    "eslint": "^8.35.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "prettier": "^2.8.4"
  }
}

**Comment by eduardoborges** [comment]
> > > Estou utilizando o hook em uma aplicação que usa Next 13.
> 
> > > A implementação segue o exemplo mostrado no readme.
> 
> > > ```
> 
> > > import { useForm } from 'react-hook-form';
> 
> > > import { useHookFormMask } from 'use-mask-input';
> 
> > > 
> 
> > > type FormType = {
> 
> > >   guest: any;
> 
> > >   cpf: string;
> 
> > > };
> 
> > > 
> 
> > > type FormProps = {
> 
> > >   submit: (data: FormType) => void;
> 
> > > };
> 
> > > 
> 
> > > const Form: FC<FormProps> = ({ submit, ...props }) => {
> 
> > >   const { register, handleSubmit } = useForm<FormType>({
> 
> > >     defaultValues: {
> 
> > >       guest: '',
> 
> > >       cpf: ''
> 
> > >     }
> 
> > >   });
> 
> > >   const registerWithMask = useHookFormMask(register);
> 
> > > 
> 
> > >   const onSubmit = (data: FormType) => {
> 
> > >     submit(data);
> 
> > >   };
> 
> > >   return (
> 
> > >     <div {...props}>
> 
> > >       <h3>titulo</h3>
> 
> > >       <form onSubmit={handleSubmit(data => onSubmit(data))}>
> 
> > >         <TextInput
> 
> > >           {...registerWithMask('cpf', 'cpf')}
> 
> > >           label='CPF'
> 
> > >         />
> 
> > > ...
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > Rodando localmente, ao carregar a página, o erro recebido é: ![image](https://user-images.githubusercontent.com/47747571/250695306-c7977e03-2b7e-4ed9-bf05-3a8edde61d19.png) ![image](https://user-images.githubusercontent.com/47747571/250695361-c8cb09cb-8bd9-4877-a6a8-0cd93bf873e2.png)
> 
> > 
> 
> > Poderia mostrar como está seu package.json?
> 
>  
> 
>  Claro:
> 
>  ```
> 
>  "dependencies": {
> 
>     "@phosphor-icons/react": "^2.0.9",
> 
>     "@stitches/react": "^1.2.8",
> 
>     "@types/node": "18.14.2",
> 
>     "@types/react": "18.0.28",
> 
>     "@types/react-dom": "18.0.11",
> 
>     "axios": "^1.3.4",
> 
>     "dotenv": "^16.0.3",
> 
>     "eslint-config-next": "13.2.1",
> 
>     "inputmask": "^5.0.9-beta.16",
> 
>     "next": "13.2.1",
> 
>     "react": "18.2.0",
> 
>     "react-dom": "18.2.0",
> 
>     "react-hook-form": "^7.43.9",
> 
>     "typescript": "4.9.5",
> 
>     "use-mask-input": "^3.3.0"
> 
>   },
> 
>   "devDependencies": {
> 
>     "@typescript-eslint/eslint-plugin": "^5.54.0",
> 
>     "@typescript-eslint/parser": "^5.54.0",
> 
>     "eslint": "^8.35.0",
> 
>     "eslint-config-airbnb": "^19.0.4",
> 
>     "eslint-config-prettier": "^8.6.0",
> 
>     "eslint-plugin-import": "^2.27.5",
> 
>     "eslint-plugin-jsx-a11y": "^6.7.1",
> 
>     "eslint-plugin-prettier": "^4.2.1",
> 
>     "eslint-plugin-react": "^7.32.2",
> 
>     "eslint-plugin-react-hooks": "^4.6.0",
> 
>     "prettier": "^2.8.4"
> 
>   }
> 
> }
> 
> ```
> 
> 
> 
> Caso ajude, quando eu tento registrar o input com a aplicação já rodando, quando o next roda o live reload só do clientSide, o hook funciona perfeitamente. Mas qualquer refresh da página, que o Next tenta gerar a página via servidor, o erro do print acima é exibido, 

Você poderia remover o inputmask das dependências e testar? Lembrando que você precisa usar o "use client" no componente, pois a lib usa o useEffect por baixo.

**Comment by NandoBruch** [comment]
> 



> > > > Estou utilizando o hook em uma aplicação que usa Next 13.
> > 
> > 
> > > > A implementação segue o exemplo mostrado no readme.
> > 
> > 
> > > >
> > 
> > 
> > > > import { useForm } from 'react-hook-form';
> > 
> > 
> > > > import { useHookFormMask } from 'use-mask-input';
> > 
> > 
> > > >
> > 
> > 
> > > > type FormType = {
> > 
> > 
> > > > guest: any;
> > 
> > 
> > > > cpf: string;
> > 
> > 
> > > > };
> > 
> > 
> > > >
> > 
> > 
> > > > type FormProps = {
> > 
> > 
> > > > submit: (data: FormType) => void;
> > 
> > 
> > > > };
> > 
> > 
> > > >
> > 
> > 
> > > > const Form: FC = ({ submit, ...props }) => {
> > 
> > 
> > > > const { register, handleSubmit } = useForm({
> > 
> > 
> > > > ```
> > > > defaultValues: {
> > > > ```
> > 
> > 
> > > > ```
> > > >   guest: '',
> > > > ```
> > 
> > 
> > > > ```
> > > >   cpf: ''
> > > > ```
> > 
> > 
> > > > ```
> > > > }
> > > > ```
> > 
> > 
> > > > });
> > 
> > 
> > > > const registerWithMask = useHookFormMask(register);
> > 
> > 
> > > >
> > 
> > 
> > > > const onSubmit = (data: FormType) => {
> > 
> > 
> > > > ```
> > > > submit(data);
> > > > ```
> > 
> > 
> > > > };
> > 
> > 
> > > > return (
> > 
> > 
> > > > ```
> > > > <div {...props}>
> > > > ```
> > 
> > 
> > > > ```
> > > >   <h3>titulo</h3>
> > > > ```
> > 
> > 
> > > > ```
> > > >   <form onSubmit={handleSubmit(data => onSubmit(data))}>
> > > > ```
> > 
> > 
> > > > ```
> > > >     <TextInput
> > > > ```
> > 
> > 
> > > > ```
> > > >       {...registerWithMask('cpf', 'cpf')}
> > > > ```
> > 
> > 
> > > > ```
> > > >       label='CPF'
> > > > ```
> > 
> > 
> > > > ```
> > > >     />
> > > > ```
> > 
> > 
> > > > ...
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Rodando localmente, ao carregar a página, o erro recebido é: ![image](https://user-images.githubusercontent.com/47747571/250695306-c7977e03-2b7e-4ed9-bf05-3a8edde61d19.png) ![image](https://user-images.githubusercontent.com/47747571/250695361-c8cb09cb-8bd9-4877-a6a8-0cd93bf873e2.png)
> > 
> > 
> > > 
> > 
> > 
> > > Poderia mostrar como está seu package.json?
> > 
> > 
> > Claro:
> > ```
> > 
> > "dependencies": {
> > 
> >    "@phosphor-icons/react": "^2.0.9",
> > 
> >    "@stitches/react": "^1.2.8",
> > 
> >    "@types/node": "18.14.2",
> > 
> >    "@types/react": "18.0.28",
> > 
> >    "@types/react-dom": "18.0.11",
> > 
> >    "axios": "^1.3.4",
> > 
> >    "dotenv": "^16.0.3",
> > 
> >    "eslint-config-next": "13.2.1",
> > 
> >    "inputmask": "^5.0.9-beta.16",
> > 
> >    "next": "13.2.1",
> > 
> >    "react": "18.2.0",
> > 
> >    "react-dom": "18.2.0",
> > 
> >    "react-hook-form": "^7.43.9",
> > 
> >    "typescript": "4.9.5",
> > 
> >    "use-mask-input": "^3.3.0"
> > 
> >  },
> > 
> >  "devDependencies": {
> > 
> >    "@typescript-eslint/eslint-plugin": "^5.54.0",
> > 
> >    "@typescript-eslint/parser": "^5.54.0",
> > 
> >    "eslint": "^8.35.0",
> > 
> >    "eslint-config-airbnb": "^19.0.4",
> > 
> >    "eslint-config-prettier": "^8.6.0",
> > 
> >    "eslint-plugin-import": "^2.27.5",
> > 
> >    "eslint-plugin-jsx-a11y": "^6.7.1",
> > 
> >    "eslint-plugin-prettier": "^4.2.1",
> > 
> >    "eslint-plugin-react": "^7.32.2",
> > 
> >    "eslint-plugin-react-hooks": "^4.6.0",
> > 
> >    "prettier": "^2.8.4"
> > 
> >  }
> > 
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Caso ajude, quando eu tento registrar o input com a aplicação já rodando, quando o next roda o live reload só do clientSide, o hook funciona perfeitamente. Mas qualquer refresh da página, que o Next tenta gerar a página via servidor, o erro do print acima é exibido,
> 
> Você poderia remover o inputmask das dependências e testar? Lembrando que você precisa usar o "use client" no componente, pois a lib usa o useEffect por baixo.

Claro! Removi a lib, criei um client component simples para fazer o teste.

```
'use client';

import { FC, InputHTMLAttributes } from 'react';
import { useForm } from 'react-hook-form';
import { useHookFormMask } from 'use-mask-input';

type InputProps = Omit<InputHTMLAttributes<HTMLInputElement>, 'type'> & {};

const TestComponent: FC<InputProps> = () => {
  const { register } = useForm();

  const registerWithMask = useHookFormMask(register);
  return (
    <form>
      <input {...registerWithMask('cpf', 'cpf')} className='input-field' />
    </form>
  );
};

export default TestComponent;
```
Fiz o teste com a lib e sem a lib instalada algumas vezes, em todos os casos o erro persiste :/

**Comment by eduardoborges** [comment]
@NandoBruch Voce poderia marcar um papo de 1horinha pra a gente ver isso em pair? Porque nao estou conseguindo pegar o problema.

[Segue o link do meu calendly](https://calendly.com/eduardoborges-inhouse)

**Comment by NandoBruch** [comment]
> @NandoBruch Voce poderia marcar um papo de 1horinha pra a gente ver isso em pair? Porque nao estou conseguindo pegar o problema.
> 
> [Segue o link do meu calendly](https://calendly.com/eduardoborges-inhouse)

Claro! Marquei lá

**Comment by sourcec0de** [comment]
@NandoBruch @eduardoborges 
Olá, qual foi o resultado dessa discussão? Estou enfrentando o mesmo problema usando o remix. Isso tem algo a ver com a renderização do lado do servidor?

**Comment by eduardoborges** [comment]
> @NandoBruch @eduardoborges 
> 
> Olá, qual foi o resultado dessa discussão? Estou enfrentando o mesmo problema usando o remix. Isso tem algo a ver com a renderização do lado do servidor?

Exatamente, isso se resolve no next com "use client".
Nunca usei Remix, posso tentar viabilizar uma correção.

**Comment by NandoBruch** [comment]
@eduardoborges Peço desculpas,  acabei não conseguindo aparecer a agenda devido a alguns problemas, será que poderíamos tentar novamente? Acabei que não consegui solucionar o problema utilizando 'use client'
