### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by AkshayPathak** [eduardoborges/use-mask-input#4]
Thanks for the library. Still getting the error below when I try npm install:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: cloud@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.x" from use-mask-input@3.0.0
npm ERR! node_modules/use-mask-input
npm ERR!   use-mask-input@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\aksha\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aksha\AppData\Local\npm-cache\_logs\2022-11-19T04_24_51_387Z-debug-0.log
```

**Comment by eduardoborges** [comment]
> Thanks for the library. Still getting the error below when I try npm install:
> 
> ```
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: cloud@0.1.0
> npm ERR! Found: react@18.2.0
> npm ERR! node_modules/react
> npm ERR!   react@"18.2.0" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^17.x" from use-mask-input@3.0.0
> npm ERR! node_modules/use-mask-input
> npm ERR!   use-mask-input@"*" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR! See C:\Users\aksha\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\aksha\AppData\Local\npm-cache\_logs\2022-11-19T04_24_51_387Z-debug-0.log
> ```

Ok, i will fix this.
