### ISSUE TITLE
Missing type=module in package.json

### ISSUE THREAD

**Issue by olafsulich** [eduardoborges/use-mask-input#44]
I ran into a problem with the library in my setup... 

It appears to be caused by a missing `type="module"` in the `package.json`, because `"main: "./dist/index.js"` points to a file of type mjs. After adding the missing `type`, everything works as it should :)

What are your thoughts? Could you add this to `package.json`?

**Comment by eduardoborges** [comment]
> I ran into a problem with the library in my setup...
> 
> It appears to be caused by a missing `type="module"` in the `package.json`, because `"main: "./dist/index.js"` points to a file of type mjs. After adding the missing `type`, everything works as it should :)
> 
> What are your thoughts? Could you add this to `package.json`?

Hey @olafsulich thanks about this.

I fixed on [3.3.1 Release](https://github.com/eduardoborges/use-mask-input/releases/tag/3.3.1).
Tell me if worked for u.

**Comment by olafsulich** [comment]
Okay, I checked that and this problem has occurred since version `3.1.0`, `3.0.6` works fine

**Comment by eduardoborges** [comment]
@olafsulich are u using vite, next or something?

**Comment by olafsulich** [comment]
@eduardoborges I'm using a custom Webpack config, but I checked it in the basic Create React App setup, and it's occurred also there

**Comment by eduardoborges** [comment]
@olafsulich I will release some beta versions, can you help me with some tests?

**Comment by olafsulich** [comment]
Sure :) 

I believe all my problems are directly related to the Inputmask library, not your library code. What I discovered is:

1. Using Create React App, you can eject (👎) and create a Webpack alias for inputmask `inputmask: "node_modules/dist/inputmask.es6.js`, then everything works correctly.
2 But if you try this with SSR React code (my custom webpack setup) it doesn't work. Then the problem is `window is not defined`, here is the issue in inputmask repo - https://github.com/RobinHerbots/Inputmask/issues/2628

**Comment by eduardoborges** [comment]
@olafsulich Im working im some workaround for these issues. :s

**Comment by eduardoborges** [comment]
@olafsulich Hey! Can you test `3.3.2-beta.1` ?

**Comment by olafsulich** [comment]
@eduardoborges Hey, I don't know how you did it, but it works perfectly! Thank you for your commitment 🙏
