### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by illumws** [eduardoborges/use-mask-input#48]
![image](https://github.com/eduardoborges/use-mask-input/assets/40471268/fe7550ab-65c6-423b-9636-b2df48d74750)

windows 11
next js 13.4.13

**Comment by eduardoborges** [comment]
> 
> 
> ![image](https://github.com/eduardoborges/use-mask-input/assets/40471268/fe7550ab-65c6-423b-9636-b2df48d74750)
> 
> 
> 
> windows 11
> 
> next js 13.4.13
> 
> 

Can you try recente 3.3.3 release? 😍

**Comment by illumws** [comment]
Work with pnpm add use-mask-input@3.3.3.
Thanks.
