### ISSUE TITLE
'Usage with React Hook Forms' correction

### ISSUE THREAD

**Issue by Berohlfs** [eduardoborges/use-mask-input#49]
Hello! My name is Bernardo. I'm from Brazil. 

First of all, I would like to thank you. Honestly, this library was exactly what I was looking for... and it really does work like a charm with react-hook-form.

There is only one extremely small issue, in the documentation, that I felt the need to point out. I may be mistaken, but my code only worked after I made the following correction:

* The `import` of `use-mask-input` shown below is incorrect. Instead of `{ withHookFormMask}`, it should be `{useHookFormMask}`. If this correction isn't made, the hook is not correctly imported ;) 

```
import React from 'react';
import { useForm } from 'react-hook-form';
import { withHookFormMask } from 'use-mask-input';

function App() {
  const { register, handleSubmit } = useForm();
  const registerWithMask = useHookFormMask(register);

  ...
```

**Comment by eduardoborges** [comment]
Hey @Berohlfs! Thank you for your contribuition.
By the way, i'm also Brazilian! _(é noiz)_.
I will fix this doc issue now.

Thank you again!
