### ISSUE TITLE
Remove 'mask trace' 

### ISSUE THREAD

**Issue by Berohlfs** [eduardoborges/use-mask-input#51]
Hello! How are you?

Is there a way to remove the mask trace from the input?

I want the text to adapt to the mask as the user types in. 

![image](https://github.com/eduardoborges/use-mask-input/assets/90404673/5c7815e0-5649-4b04-b956-5c3116f026c6)

**Comment by Berohlfs** [comment]
Thank you!!!

**Comment by eduardoborges** [comment]
@Berohlfs plz update to latest version. Has a lot of typing's enhancements.

**Comment by luisfelipe-dev** [comment]
Poderia melhorar esse nome ein rapaziada me matei pra encontrar esse carai.. jitMasking foi de lascar kkk poderia usar o maskChar igual os outros padrões! abraço

**Comment by eduardoborges** [comment]
> Poderia melhorar esse nome ein rapaziada me matei pra encontrar esse carai.. jitMasking foi de lascar kkk poderia usar o maskChar igual os outros padrões! abraço

Hey @luisfelipe-dev eu concordo! Hahah. mas esse termo jit é bem usado por ai (just in time). Segui o padrao.

**Comment by luisfelipe-dev** [comment]
@eduardoborges quando der adiciona um exemplo no readme acho que esse cara é o mais buscado pela galera
