### ISSUE TITLE
Still don't get auto completion for options after last update (?)

### ISSUE THREAD

**Issue by rafma0** [eduardoborges/use-mask-input#53]
This is just weird, after updating my `use-mask-input` to `3.3.4`, TS still can't figure options types for `registerWithMask` if I do
```ts
import { useHookFormMask } from 'use-mask-input'
```
![image](https://github.com/eduardoborges/use-mask-input/assets/28578847/7fd6f932-52af-4100-ab3f-1f29d8d467db)

but with my cloned updated repo, if I do `npx rollup -c --watch` and then
```ts
import { useHookFormMask } from '/local/path/to/use-mask-input/dist'
```
![image](https://github.com/eduardoborges/use-mask-input/assets/28578847/08335c13-3e22-470d-97d4-3ce4446772ab)

any ideas?

**Comment by eduardoborges** [comment]
hey @rafma0 can you try `3.3.5` release?

https://github.com/eduardoborges/use-mask-input/releases/tag/3.3.5

**Comment by rafma0** [comment]
Looks perfect now 🎉
