### ISSUE TITLE
error - ReferenceError: self is not defined

### ISSUE THREAD

**Issue by rserafim** [eduardoborges/use-mask-input#6]
Estou recebendo este erro no terminal

error - ReferenceError: self is not defined.

  "dependencies": {
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.41.5",
    "use-mask-input": "^3.0.1",
    "yup": "^0.32.11"
  },

A esse WARN npm WARN deprecated lodash.compose@2.4.1: This package is discontinued. Use lodash.flowright@^3.0.0.

**Comment by eduardoborges** [comment]
> flowright

Opa, muito obrigado pela contribuição. Acabei de subir a correção.
