### ISSUE TITLE
Component unmount

### ISSUE THREAD

**Issue by z1m1n** [eduardoborges/use-mask-input#7]
Hi!

I'm using `withHookFormMask` function and got some problem with component unmount. Is there any way to destroy inputmask on component unmount? I tried to call `input.inputmask.remove()` manually, but it is not solve the issue.

![image](https://user-images.githubusercontent.com/5075434/217654874-32f08758-8252-401c-9c3c-2ab24c312dd5.png)

**Comment by eduardoborges** [comment]
> Hi!
> 
> 
> 
> I'm using `withHookFormMask` function and got some problem with component unmount. Is there any way to destroy inputmask on component unmount? I tried to call `input.inputmask.remove()` manually, but it is not solve the issue.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/5075434/217654874-32f08758-8252-401c-9c3c-2ab24c312dd5.png)
> 
> 

Hey, i will investigate this problem tomorrow. Thanks 😊
