### ISSUE TITLE
 Problems with mask behavior when using 'a' or '*' for the mask template.

### ISSUE THREAD

**Issue by Ilwel** [eduardoborges/use-mask-input#73]
When I use 'a' or '*' for the mask template, upon pressing 'Backspace' or 'Delete', the input is filled with 'B' or 'D', respectively.

I am using version 3.3.7, which I believe is the latest one.

![image](https://github.com/eduardoborges/use-mask-input/assets/38703179/4634c50b-8be8-45ee-b181-ab359236a62f)

![image](https://github.com/eduardoborges/use-mask-input/assets/38703179/534f6d3f-5d6e-46a0-a196-0df0696c9728)

**Comment by 4lisson777** [comment]
Same here! @eduardoborges

**Comment by eduardoborges** [comment]
Hey @Ilwel . You need to add to the mask who many "any" digits you want, min and max:

```js
<input mask={"*{1,2}"}
```

**Comment by 4lisson777** [comment]
@eduardoborges I have this 'B' or 'D' when I try to delete the text, but I'm using this mask here -> 99999999-A. Can you help me please? :(

**Comment by garabedium** [comment]
@eduardoborges. I'm seeing the same issue with the hook. On Backspace changes the first character to a B. Command + Backspace succeeds in clearing the input. 

`const registerWithMask = useHookFormMask(register);`

```
      <input
        {...registerWithMask("testZip", "A{1}9A{1} 9A{1}9")}
        type="text"
      />
 ```
