### ISSUE TITLE
Heavy library

### ISSUE THREAD

**Issue by brunowego** [eduardoborges/use-mask-input#79]
Your library fits perfectly into my stack, and is the best library that I have tested, but it's a heavy library. Maybe adding a `.min.js` version would solve this.

<img width="586" alt="Screenshot 2024-04-20 at 5 22 35 PM" src="https://github.com/eduardoborges/use-mask-input/assets/441774/a32d7c12-dc5a-445b-90e3-1f5122ef1ac7">

**Comment by eduardoborges** [comment]
hey @brunowego i know, sadly is because of a dependency. but, the good news is: im working on a v4 with a lot of functionalities and small bundle size.

**Comment by brunowego** [comment]
This is amazing, thank you @eduardoborges !
