### ISSUE TITLE
next.js - self is not defined

### ISSUE THREAD

**Issue by ciruz** [eduardoborges/use-mask-input#9]
Hey nice work,

I try to use `use-mask-input`with `react-hook-form` and `next.js`, sadly I get this reference error, since Web-APIs are not available on the server side.

```
ReferenceError: self is not defined
    at eval (webpack-internal:///(sc_client)/./node_modules/use-mask-input/node_modules/inputmask/dist/inputmask.js:10:3)
    at (sc_client)/./node_modules/use-mask-input/node_modules/inputmask/dist/inputmask.js
```

Any plans to make it compatible with next.js?

Thank you

PS: If somebody wants to use it , but has the same error, just load your form with  ``next/dynamic`` and ``ssr: false``.

**Comment by ciruz** [comment]
Hey @eduardoborges,

nice, thanks. I think if you first check if window is available, it should be fixed and compatible. Something like:

```javascript
if (typeof window !== 'undefined') {
  // your code
}
```

**Comment by eduardoborges** [comment]
Uh make sense lol 😂

**Comment by eduardoborges** [comment]
> Hey @eduardoborges,
> 
> nice, thanks. I think if you first check if window is available, it should be fixed and compatible. Something like:
> 
> ```js
> if (typeof window !== 'undefined') {
>   // your code
> }
> ```

Hey, i make experiments, but... this problem happen when i need to load inputmask. 
We need to find a way to load condicionaly :/

**Comment by ciruz** [comment]
Sounds like an issue with inputmask itself then, or?

**Comment by sergirams** [comment]
I resolved this issue changing the input type to "text"

**Comment by jlucaso1** [comment]
Hi @eduardoborges, I think in the new version of inputmask this is resolved:
https://github.com/RobinHerbots/Inputmask/pull/2663
Can you confirm this and update?

**Comment by eduardoborges** [comment]
> Hi @eduardoborges, I think in the new version of inputmask this is resolved: [RobinHerbots/Inputmask#2663](https://github.com/RobinHerbots/Inputmask/pull/2663) Can you confirm this and update?

Hey, not solve the problem, but apear another.
I opened an PR for solve that.

RobinHerbots/Inputmask#2709

**Comment by eduardoborges** [comment]
Hey guys! good news! Latest version of beta of inputmask solves the problems with NextJs.

Upgrate to [3.2.0](https://github.com/eduardoborges/use-mask-input/releases/tag/3.2.0)

@jlucaso1 @ciruz

**Comment by ciruz** [comment]
Thank you very much

**Comment by lobatolais** [comment]
Thank you so much, @eduardoborges! <3 It may be worth updating the documentation to include the information that compatibility with Next.js is now supported.

**Comment by eduardoborges** [comment]
> Thank you so much, @eduardoborges! <3 It may be worth updating the documentation to include the information that compatibility with Next.js is now supported.

Yeah! I will do this!

Im working on new simplified API 👀 and fresh new and more compleat documentation. 😻
